# Generated by Django 3.1.4 on 2022-04-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0008_remove_replie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replie',
            old_name='user',
            new_name='user2',
        ),
    ]
