# Generated by Django 3.1.4 on 2022-04-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0009_auto_20220419_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png', null=True, upload_to='post'),
        ),
    ]
