# Generated by Django 3.1.4 on 2022-04-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0010_auto_20220422_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blackblue.gif', null=True, upload_to='post'),
        ),
    ]
