# Generated by Django 3.1.4 on 2022-04-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0011_auto_20220422_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media1/post/blackblue.gif', null=True, upload_to='post'),
        ),
    ]
